Update 80probe.py for Python 3+
Python 3.6.1 does not like like 20

  File "./80probe.py", line 20
    except Exception, e:
                    ^
SyntaxError: invalid syntax

changed from "except Exception, e:" to "except Exception as e:" and it works perfectly.